server {
    server_name matrix.bosunpkm.com;

    location / {
        proxy_pass http://127.0.0.1:8008;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Matrix federation redirects
    location /.well-known/matrix/server {
        default_type application/json;
        return 200 '{"m.server": "matrix.bosunpkm.com:443"}';
        add_header Access-Control-Allow-Origin *;
    }

    location /.well-known/matrix/client {
        default_type application/json;
        return 200 '{"m.homeserver": {"base_url": "https://matrix.bosunpkm.com"}}';
        add_header Access-Control-Allow-Origin *;
    }

    listen [::]:443 ssl;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/matrix.bosunpkm.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/matrix.bosunpkm.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}
server {
    if ($host = matrix.bosunpkm.com) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name matrix.bosunpkm.com;
    return 404;
}
